Repository COSC481W-2023Fall/SAIO, pull requests merged in 2023-10, with the labels that each got.

#15 Hello world react
  frontend/src/App.jsx
  frontend/src/__tests__/sum.test.jsx
  frontend/src/components/BasicTemplateComponent.jsx
  frontend/src/components/index.jsx
  frontend/src/components/sum.jsx
  frontend/src/contexts/ContextProvider.jsx
  frontend/src/main.jsx
  frontend/src/pages/BasicTemplatePage.jsx
  frontend/src/pages/index.jsx
Labels: hello world

#19 Deren react backend connection
  frontend/src/App.jsx
  frontend/src/components/pages/Notes.jsx
Labels: bug, react, feature, sprint 1

#16 feat: Added Account Creation
  backend/app.py
  backend/requirements.txt
  frontend/src/App.jsx
  frontend/src/components/pages/RegisterForm.jsx
  frontend/src/main.jsx
  frontend/src/pages/index.jsx
Labels: react, feature, fastapi, mongodb, sprint 1

#45 Deren fix cors
  backend/requirements.txt
  backend/src/app.py
  backend/src/dbfuncs/student_db_funks.py
  backend/src/models/student_model.py
  backend/src/paths/student_routes.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.jsx
  frontend/src/pages/app/Notes.jsx
Labels: bug
