Repository COSC481W-2023Fall/SAIO, pull requests merged in 2023-11, with the labels that each got.

#47 Notes Applet Backend (FastAPI and MongoDB)
  backend/src/app.py
  backend/src/dbfuncs/notes.py
  backend/src/models/common.py
  backend/src/models/notes.py
  backend/src/paths/app/notes.py
Labels: feature, fastapi, mongodb

#48 Deren - Calendar app Backend
  backend/src/app.py
  backend/src/dbfuncs/calendar_db_funks.py
  backend/src/models/calendar_model.py
  backend/src/paths/app/calendar_routes.py
Labels: feature, fastapi, mongodb

#49 📔✏️Notes Applet Frontend
  backend/src/dbfuncs/notes.py
  backend/src/models/notes.py
  backend/src/paths/app/notes.py
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/SaveButton.jsx
  frontend/src/components/notes/EditorButton.jsx
  frontend/src/components/notes/NeighborContainer.jsx
  frontend/src/components/notes/NeighborNote.jsx
  frontend/src/components/notes/NewNoteButton.jsx
  frontend/src/components/notes/NotesBody.jsx
  frontend/src/components/notes/NotesTitle.jsx
  frontend/src/config.js
  frontend/src/pages/Login.jsx
  frontend/src/pages/app/Notes.jsx
  frontend/src/scripts/saveNote.js
  frontend/vite.config.js
Labels: react, feature, fastapi, mongodb

#54 Deren calendar app frontend
  backend/src/dbfuncs/calendar_db_funks.py
  backend/src/paths/app/calendar_routes.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/main.jsx
  frontend/src/pages/app/Calendar.jsx
  frontend/src/pages/app/CalendarApp.jsx
  frontend/src/pages/index.jsx
Labels: react, feature

#53 Lennon edit account page
  backend/src/app.py
  backend/src/dbfuncs/edit.py
  backend/src/models/UserEdit.py
  backend/src/paths/edit.py
  backend/src/paths/login.py
  backend/src/paths/signup.py
  frontend/src/App.jsx
  frontend/src/pages/EditAccount.jsx
Labels: react, feature, fastapi

#55 Deren Updating URLs
  frontend/src/pages/app/CalendarApp.jsx
Labels: optimizaton, react

#60 Deren calendar front back unit tests
  backend/test/test_calendar_app.py
  frontend/src/__tests__/Calendar.test.jsx
  frontend/src/__tests__/CalendarApp.test.jsx
Labels: react, fastapi

#66 Deren color themes
  frontend/public/images/icons/apps/colorthemepalette.png
  frontend/src/App.jsx
  frontend/src/components/ThemeButton.jsx
  frontend/src/components/setColorTheme.js
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/pages/app/CalendarApp.jsx
  frontend/src/pages/app/ColorThemePalette.jsx
  frontend/src/pages/app/DisplayFlashcards.jsx
  frontend/src/pages/app/Home.jsx
  frontend/src/pages/app/Notes.jsx
  frontend/src/pages/app/Todo.jsx
  frontend/src/style/App.css
  frontend/src/style/Navbar.css
Labels: react, feature

#67 Sam Style Revamp
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/icons/apps/notes.png
  frontend/public/images/icons/construction.png
  frontend/src/App.jsx
  frontend/src/components/ThemeButton.jsx
  frontend/src/components/flashcards/DisplayFlashcards.jsx
  frontend/src/components/flashcards/FlashcardManagment.jsx
  frontend/src/components/index.jsx
  frontend/src/components/notes/NeighborNote.jsx
  frontend/src/components/notes/SaveButton.jsx
  frontend/src/components/sidebar/NavTab.jsx
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/sidebar/SidebarToggle.jsx
  frontend/src/components/todo/TodoList.jsx
  frontend/src/main.jsx
  frontend/src/pages/AppLayout.jsx
  frontend/src/pages/EditAccount.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/app/CalendarApp.jsx
  frontend/src/pages/app/ColorThemePalette.jsx
  frontend/src/pages/app/DisplayFlashcards.jsx
  frontend/src/pages/app/FlashcardManagment.jsx
  frontend/src/pages/app/Home.jsx
  frontend/src/pages/app/Notes.jsx
  frontend/src/pages/app/Todo.jsx
  frontend/src/scripts/setColorTheme.js
  frontend/src/style/App.css
  frontend/src/style/Navbar.css
  frontend/src/style/TodoApp.css
  frontend/src/style/index.css
  frontend/src/style/sidebar.css
  frontend/src/style/standard.css
  frontend/src/style/themes/standard_light.css
Labels: visual improvement, react, feature

#69 Lennon add token authentication
  backend/requirements.txt
  backend/src/dbfuncs/categories.py
  backend/src/dbfuncs/flashcards.py
  backend/src/models/Token.py
  backend/src/models/calendar_model.py
  backend/src/package-lock.json
  backend/src/paths/app/categories.py
  backend/src/paths/app/flashcards.py
  backend/src/paths/login.py
  backend/src/paths/todo.py
  frontend/src/App.jsx
  frontend/src/components/PrivateRoute.jsx
  frontend/src/components/flashcards/DisplayFlashcards.jsx
  frontend/src/components/flashcards/FlashcardManagment.jsx
  frontend/src/components/todo/TodoForm.jsx
  frontend/src/components/todo/TodoList.jsx
  frontend/src/config.js
  frontend/src/pages/Login.jsx
  frontend/src/pages/Signup.jsx
  frontend/src/pages/app/Home.jsx
Labels: react, feature, fastapi

#76 Deren beta calendar updates
  frontend/src/components/ThemeButton.jsx
  frontend/src/pages/app/CalendarApp.jsx
  frontend/src/pages/app/ColorThemePalette.jsx
  frontend/src/style/App.css
Labels: bug, visual improvement

#77 Sam redo light dark mode
  frontend/index.html
  frontend/src/components/ThemeButton.jsx
  frontend/src/components/notes/EditorButton.jsx
  frontend/src/components/notes/NeighborContainer.jsx
  frontend/src/components/notes/NeighborNote.jsx
  frontend/src/components/notes/NewNoteButton.jsx
  frontend/src/components/notes/NotesBody.jsx
  frontend/src/components/notes/NotesTitle.jsx
  frontend/src/components/notes/SaveButton.jsx
  frontend/src/components/sidebar/NavTab.jsx
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/sidebar/SidebarToggle.jsx
  frontend/src/pages/AppLayout.jsx
  frontend/src/pages/app/Home.jsx
  frontend/src/pages/app/Notes.jsx
  frontend/src/scripts/setColorTheme.js
  frontend/src/style/App.css
  frontend/src/style/TodoApp.css
  frontend/src/style/sidebar.css
Labels: visual improvement
